[project]
name = "global"
version = "0.1.0"
description = "my global python scope"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.0",
    "git-filter-repo>=2.47.0",
    "google-genai>=1.12.1",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.4.1",
    "polars[pyarrow]>=1.30.0",
]
