directory: "/home/pascalwhoop/tank/Music/"
import:
    move: yes
    write: yes
    #    none_rec_action: skip
    incremental: yes
    resume: ask
    bell: yes
    from_scrath: yes
    group_albums: yes
plugins: lastgenre fromfilename scrub plexupdate duplicates chroma
plex:
    host: "localhost"
    port: 32400
    token: "BnY3AvppWhYNN66jaVkF"
    #chroma:
    #    auto: yes
    #musicbrainz:
    #    host: localhost:5000
    #    ratelimit: 1000
match:
    strong_rec_thresh: 0.15 #means 70% at least
    distance_weights:
        missing_tracks: 0.1
    max_rec:
        missing_tracks: strong
        unmatched_tracks: strong
        #    preferred:
        #        countries: ['US', 'GB|UK']
        #        media: ['CD', 'Digital Media|File']
        #        original_year: yes
